ALTER TABLE BUDDY ADD COLUMN COMETID TEXT DEFAULT "";
ALTER TABLE BUDDY ADD COLUMN LASTSEEN TEXT DEFAULT "";
ALTER TABLE ONE_ON_ONE_MESSAGE ADD COLUMN MESSAGETICK INT DEFAULT 1;
ALTER TABLE BUDDY ADD COLUMN LSTN INT DEFAULT 0;